### PR TITLE
#60 Estimate project size

### PR DESCRIPTION
**Pull request by super132**
For task #60, provide estimate for jcabi-aether.

### CODE REVIEW

**Comment by super132** [comment]
@dmarkov , please review this PR. Thanks.

**Comment by dmarkov** [comment]
@super132 Thanks, someone will review your pull request soon

**Comment by dmarkov** [comment]
@pinaf please review, thanks

**Comment by dmarkov** [comment]
> @dmarkov , please review this PR. Thanks.

@super132 thanks, I'll take a look

**Comment by pinaf** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor merge pls

**Comment by dmarkov** [comment]
@pinaf Many thanks! **16 mins** were added to your account in Transaction ID `AP-4K104785JW200533D` (task took 21 hours and 24 mins)

review comments (c=1) added as a bonus

added +16 to your rating, now it is equal to [+7905](http://www.netbout.com/b/35128?open=rating)

**Comment by dmarkov** [comment]
@rultor deploy

**Pull request merged**
