### PR TITLE
#21

### PR DESCRIPTION
**Pull request by pinaf**
Issue #21

### CODE REVIEW

**Comment by dmarkov** [comment]
Thanks for the pull request, let me find a reviewer..

**Comment by dmarkov** [comment]
@longtimeago could you please review this pull request

**Comment by longtimeago** [comment]
@rultor please, merge

**Comment by yegor256** [comment]
@rultor try to merge it

**Comment by dmarkov** [comment]
@longtimeago **15 mins** was added to your account, many thanks for your contribution!; +15 to your rating, your total score is [+1259](http://www.netbout.com/b/35024?open=rating)

**Comment by dmarkov** [comment]
@rultor deploy pls

**Pull request merged**
