### PR TITLE
#41: Source code from master doesn't pass qulice check.

### PR DESCRIPTION
**Pull request by pandreev**
please review

### CODE REVIEW

**Comment by dmarkov** [comment]
Let me find a reviewer for this pull request, thanks for submitting it

**Comment by dmarkov** [comment]
@yegor256 please review this one

**Comment by yegor256** [comment]
@pandreev hm... the changes looks very strange. are you sure it's not a mistake?

**Comment by pandreev** [comment]
@yegor256 The task is to make the code pass the qulice check. The build fails with two main reasons:
[ERROR] Lines in file should end with Unix-like end of line (RegexpMultilineCheck)
[ERROR] Line does not match expected header line of ' *'. (HeaderCheck)

The reason for the first error is that the Win-like end of line should be substituted with a Unix-like.
The reason for the second error is that there need to be a empty line between each two lines in the header and three empty lines between paragraphs in the header. This looks weird to me, but this is according to qulice.

After those two changes the code passes the qulice check.

**Comment by yegor256** [comment]
It passes all checks only because you're working on Windows. On Linux it will fail, see https://travis-ci.org/jcabi/jcabi-aether/builds/45716369

**Comment by pandreev** [comment]
@yegor256 Ok, that diff in OS is strange to me. Anyway the headers are foxed and tested in Ubuntu. Now qulice check passes successfully.

**Comment by yegor256** [comment]
@pandreev now we have zero changes in the pull request :) we can merge it, no problem, but it won't do anything, as I understand

**Comment by yegor256** [comment]
@pandreev are you planning to finish this pull request? if no, please close it

**Comment by pandreev** [comment]
Sorry, no Internet at home last two months.

**Comment by dmarkov** [comment]
@yegor256 thanks, I just added **19 mins** to your account, payment `000-129914b3`

you're getting extra minutes here (c=4)

+19 added to your rating, at the moment it is: [+7364](http://www.netbout.com/b/35008?open=rating)

**Pull request closed without merging**
