### PR TITLE
Removed puzzle for issue #78

### PR DESCRIPTION
**Pull request by amihaiemil**
In the previous PR that solved issue #78 I had forgotten to remove the puzzle.
In this PR I removed the puzzle.

### CODE REVIEW

**Comment by amihaiemil** [comment]
@yegor256 Can you merge this right away, or is it mandatory to wait for Dan to assign a reviewer? It's only to remove the puzzle so the ticket #78 can be closed.

**Comment by yegor256** [comment]
@rultor merge

**Comment by amihaiemil** [comment]
@yegor256 apparently rultor does not have rights to access Maven (http://repo.maven.apache.org/maven2) ? The same exception were thrown when the previous PR was deployes by Dan. Is there something wrong on rultor's side?

**Comment by original-brownbear** [comment]
@amihaiemil I created #82 explaining what's going on here. This is something that needs to be fixed here not in Rultor I fear.

**Comment by amihaiemil** [comment]
@original-brownbear I read your issue, but I must admit I don't understand what needs to be done (I have 0 experience with dev-ops stuff like Docker... for instance what do you mean when you say "image"?) I have the feeling that it's a 5 minutes job for someone who know what they' re doing, while it would take me as a newbie much more time and I would probably break something... I'll ask the PM to put this PR and its issue on hold until issue #82 is solved.

**Comment by dmarkov** [comment]
@amihaiemil Thanks for your pull request, let me find someone who can review it

**Comment by dmarkov** [comment]
@yegor256 review this pull request please, it is rather short for a full review

**Comment by yegor256** [comment]
@rultor try to merge again, maybe will work

**Comment by amihaiemil** [comment]
@yegor256 Issue #82 was closed, can we try to merge this again? Thanks.

**Comment by yegor256** [comment]
@rultor try to merge

**Comment by amihaiemil** [comment]
@yegor256 I saw you fixed the ``&&`` typos in the Dockerfile. Can we try another merge? Thanks.

**Comment by yegor256** [comment]
@rultor try to merge

**Comment by dmarkov** [comment]
@yegor256 **19 mins** was added to your account, many thanks for your contribution (payment 000-9b3928d9)! The task took 1272 hours and 21 mins.. extra minutes for review comments (c=4). +19 to your rating, your total score is [+1599](http://www.netbout.com/b/35008?open=rating)

**Comment by dmarkov** [comment]
@rultor please deploy

**Pull request merged**
