### PR TITLE
 #48 - Wrong management of dependencies duplicated in multiple versions

### PR DESCRIPTION
**Pull request by maurezen**

### CODE REVIEW

**Comment by dmarkov** [comment]
Thanks, someone will review your pull request soon

**Comment by dmarkov** [comment]
@krzyk please review, thanks

**Comment by krzyk** [comment]
@maurezen please add a unit test for this

**Comment by maurezen** [comment]
@krzyk updated the `ClasspathTest#returnsArtifactWithHighestVersionNumber` test.

**Comment by krzyk** [comment]
@maurezen right now the test looks almost the same as previously so I don't think it tests this case.
First of all such test would have to match that the older artifact is not in the classpath and the newer one is in it. And of course it has to fail before the else is added.

**Comment by maurezen** [comment]
@krzyk right reshuffled the artefact addition order and added a check that only one version of the artefact is in the classpath.

**Comment by krzyk** [comment]
@maurezen when I tried your test without the change in `Classpath` it suceeded, so it doesn't test this case (because it should fail if `Classpath` is without the `else`)

**Comment by maurezen** [comment]
@krzyk you're right. Update the test (and the logic of the Classpath as well).

**Comment by krzyk** [comment]
@rultor merge pls

**Comment by yegor256** [comment]
@rultor merge

**Comment by dmarkov** [comment]
@krzyk Much appreciated! **17 mins** was added to your account, payment ID `51571526`

+17 added to your rating, current score is: [+3929](http://www.netbout.com/b/35035?open=rating)

**Comment by dmarkov** [comment]
@rultor deploy pls

**Pull request merged**
