### PR TITLE
PR for issue #41

### PR DESCRIPTION
**Pull request by dpisarenko**
Issue https://github.com/jcabi/jcabi-aether/issues/41

### CODE REVIEW

**Comment by alevohin** [comment]
@dpisarenko thanks, your instruction works. But I think the better solution is add file .gitattributes
as described here: https://help.github.com/articles/dealing-with-line-endings/ to disable core.autocrlf only for this repo.

**Comment by dpisarenko** [comment]
@alevohin I added the `.gitattributes` file.

**Comment by dmarkov** [comment]
Thanks, I'll find someone to review this PR soon

**Comment by dmarkov** [comment]
@carlosmiranda please review this one

**Comment by carlosmiranda** [comment]
@rultor Let's merge please

**Comment by yegor256** [comment]
@rultor merge it

**Comment by dmarkov** [comment]
@carlosmiranda I added **18 mins** to your account, many thanks for working with the project!. +18 added to your rating, at the moment it is: [+1456](http://www.netbout.com/b/35023?open=rating)

**Comment by dmarkov** [comment]
@rultor please deploy

**Pull request merged**
