### PR TITLE
#57 modified .gitattributes file for Unix-like end of line

### PR DESCRIPTION
**Pull request by simonjenga**
#57 modified .gitattributes file for Unix-like end of line

### CODE REVIEW

**Comment by dmarkov** [comment]
Many thanks, I will find someone to review it before we merge

**Comment by dmarkov** [comment]
@krzyk please review, thanks

**Comment by krzyk** [comment]
@rultor merge pls

**Comment by yegor256** [comment]
@rultor merge

**Comment by dmarkov** [comment]
@krzyk Thanks a lot, I just topped your account for **16 mins**, transaction ID `53409538`; you're getting extra minutes here (c=1); +16 to your rating, your total score is [+5155](http://www.netbout.com/b/35035?open=rating)

**Comment by dmarkov** [comment]
@rultor deploy

**Pull request merged**
