### PR TITLE
Issue40

### PR DESCRIPTION
**Pull request by alevohin**
MavenClasspathTest.java:101-101: Add handling of broken dependencies

### CODE REVIEW

**Comment by dmarkov** [comment]
I'll find a reviewer for your pull requests shortly, thanks for contribution!

**Comment by dmarkov** [comment]
@yegor256 please review

**Comment by yegor256** [comment]
@rultor looks good, merge pls

**Comment by yegor256** [comment]
@alevohin if you want me to review the pull request again, say so (post a msg here). Github doesn't notify me when you push to the branch

**Comment by alevohin** [comment]
@yegor256 please review this pull request again.

**Comment by yegor256** [comment]
@rultor try to merge again

**Pull request merged**
