### PR TITLE
license year updated

### PR DESCRIPTION
**Pull request by simonjenga**
license year updated

### CODE REVIEW

**Comment by dmarkov** [comment]
Thanks for your pull request, let me find someone who can review it

**Comment by dmarkov** [comment]
@pinaf review this one please

**Comment by pinaf** [comment]
@simonjenga I see many files which still have 2014: Here is the list:

>
./LICENSE.txt:Copyright (c) 2012-2014, jcabi.com
./src/aws-it/aether-test/client/pom.xml: * Copyright (c) 2012-2014, jcabi.com
./src/aws-it/aether-test/plugin/pom.xml: * Copyright (c) 2012-2014, jcabi.com
./src/aws-it/aether-test/plugin/src/main/java/com/jcabi/aether/plugin/RunMojo.java: * Copyright (c) 2012-2014, jcabi.com
./src/aws-it/aether-test/plugin/src/main/java/com/jcabi/aether/plugin/package-info.java: * Copyright (c) 2012-2014, jcabi.com
./src/aws-it/aether-test/pom.xml: * Copyright (c) 2012-2014, jcabi.com
./src/changes/changes.xml: * Copyright (c) 2012-2014, jcabi.com
./src/it/basic-usage/pom.xml: * Copyright (c) 2012-2014, jcabi.com
./src/it/basic-usage/src/test/java/com/jcabi/AetherTest.java: * Copyright (c) 2012-2014, jcabi.com
./src/it/basic-usage/src/test/java/com/jcabi/package-info.java: * Copyright (c) 2012-2014, jcabi.com
./src/it/basic-usage/src/test/resources/log4j.properties:# Copyright (c) 2012-2014, jcabi.com
./src/it/mirror-usage/pom.xml: * Copyright (c) 2012-2014, jcabi.com
./src/it/mirror-usage/src/test/java/com/jcabi/AetherTest.java: * Copyright (c) 2012-2014, jcabi.com
./src/it/mirror-usage/src/test/java/com/jcabi/package-info.java: * Copyright (c) 2012-2014, jcabi.com
./src/it/mirror-usage/src/test/resources/log4j.properties:# Copyright (c) 2012-2014, jcabi.com
./src/it/mirror-usage/verify.groovy: * Copyright (c) 2012-2014, jcabi.com
./src/it/settings.xml: * Copyright (c) 2012-2014, jcabi.com
./src/main/java/com/jcabi/aether/AmazonWagonProvider.java: * Copyright (c) 2012-2014, jcabi.com
./src/main/java/com/jcabi/aether/LogTransferListener.java: * Copyright (c) 2012-2014, jcabi.com
./src/main/java/com/jcabi/aether/MavenClasspath.java: * Copyright (c) 2012-2014, jcabi.com
./src/main/java/com/jcabi/aether/MavenRootArtifact.java: * Copyright (c) 2012-2014, jcabi.com
./src/main/java/com/jcabi/aether/RepositorySystemBuilder.java: * Copyright (c) 2012-2014, jcabi.com
./src/main/java/com/jcabi/aether/RootArtifact.java: * Copyright (c) 2012-2014, jcabi.com
./src/main/java/com/jcabi/aether/package-info.java: * Copyright (c) 2012-2014, jcabi.com
./src/main/java/com/jcabi/aether/Repository.java: * Copyright (c) 2012-2014, jcabi.com
./src/main/java/com/jcabi/aether/RepositoryProxy.java: * Copyright (c) 2012-2014, jcabi.com
./src/main/java/com/jcabi/aether/SimpleRepository.java: * Copyright (c) 2012-2014, jcabi.com
./src/main/java/com/jcabi/aether/Classpath.java: * Copyright (c) 2012-2014, jcabi.com
./src/main/java/com/jcabi/aether/Aether.java: * Copyright (c) 2012-2014, jcabi.com
./src/main/java/com/jcabi/aether/RepositoryAuthentication.java: * Copyright (c) 2012-2014, jcabi.com
./src/site/apt/example-classpath.apt.vm:~~ Copyright (c) 2012-2014, jcabi.com
./src/site/apt/index.apt.vm:~~ Copyright (c) 2012-2014, jcabi.com
./src/site/site.xml: * Copyright (c) 2012-2014, jcabi.com
./src/test/java/com/jcabi/aether/AetherTest.java: * Copyright (c) 2012-2014, jcabi.com
./src/test/java/com/jcabi/aether/MavenClasspathTest.java: * Copyright (c) 2012-2014, jcabi.com
./src/test/java/com/jcabi/aether/MavenRootArtifactTest.java: * Copyright (c) 2012-2014, jcabi.com
./src/test/java/com/jcabi/aether/RootArtifactTest.java: * Copyright (c) 2012-2014, jcabi.com
./src/test/java/com/jcabi/aether/package-info.java: * Copyright (c) 2012-2014, jcabi.com
./src/test/java/com/jcabi/aether/ClasspathTest.java: * Copyright (c) 2012-2014, jcabi.com
./src/test/resources/log4j.properties:# Copyright (c) 2012-2014, jcabi.com
./pom.xml: * Copyright (c) 2012-2014, jcabi.com

**Comment by pinaf** [comment]
@maurezen I suppose this is for the issue you created in #44 
Would you agree all files above should be updated also?

**Comment by maurezen** [comment]
@pinaf yes, these should also be updated.

**Comment by pinaf** [comment]
@maurezen thanks

**Comment by pinaf** [comment]
@simonjenga please update those items above as well

**Comment by simonjenga** [comment]
@pinaf I don't understand you. I have updated all the relevant files to 2015 locally in my branch, commited and submitted the pull request. I don't see any which isn't updated yet :)

```
.\javaworkspace\jcabi-aether>git push origin 44
Everything up-to-date

.\javaworkspace\jcabi-aether>git status
On branch 44
nothing to commit, working directory clean
```
Please look at: https://github.com/simonjenga/jcabi-aether/commit/f4068d2f99f0c08310f5e035e725d6ae9d13f58d

Or am i missing something?

**Comment by pinaf** [comment]
@simonjenga you are right - my mistake. sorry about that.

**Comment by pinaf** [comment]
@rultor merge please

**Comment by pinaf** [comment]
@dmarkov @yegor256 rultor just asked @dmarkov  for merge permission. not sure this is correct.

**Comment by yegor256** [comment]
@rultor merge it

**Comment by simonjenga** [comment]
Thanks all

**Comment by dmarkov** [comment]
@pinaf Thank you, I have added **15 mins** to your account in payment/transaction "`AP-8J067884D68915424`"

added +15 to your rating, now it is equal to [+4390](http://www.netbout.com/b/35128?open=rating)

**Comment by dmarkov** [comment]
@rultor please deploy

**Pull request merged**
