### PR TITLE
Changed @NotNull to Validate.notNull() in Aether.jara

### PR DESCRIPTION
**Pull request by amihaiemil**
This PR is for issue #78 . Build under openjdk6 (and oraclejdk6) fails when ``javax.validation.constraints.@NotNull`` is used for validation, so I used ``org.apache.commons.lang3.Validate.notNull()`` instead.

### CODE REVIEW

**Comment by dmarkov** [comment]
@amihaiemil Many thanks for the PR, let me find a reviewer for it

**Comment by dmarkov** [comment]
@pinaf please review this PR

**Comment by pinaf** [comment]
@amihaiemil looks good, just not sure whether we should even have these validations since they were removed in another project. @yegor256 please advise on whether these validations should be removed or whether this solution is fine.

**Comment by yegor256** [comment]
@amihaiemil let's just remove them at all. see http://www.yegor256.com/2016/01/26/defensive-programming.html

**Comment by amihaiemil** [comment]
@pinaf Done. Scope of the validation-api dependency is set to ``<scope>test</scope>`` as for the others, since the check complains of unused dependencies in the final build (validation-api jar comes from jcabi-parent).

**Comment by pinaf** [comment]
@amihaiemil I see. Can't we add `<exclusions><exclusion>...</exclusion></exclusions>` to the jcabi-parent dependency?

**Comment by amihaiemil** [comment]
@pinaf I think that should also do it. I will try as soon as possible, later today.

**Comment by amihaiemil** [comment]
@pinaf I tried but you cannot exclude dependencies that are inherited from the pom parent. The ``<exclusions>`` child is not even accepted by a ``<parent>`` element, only by a ``<dependency>`` element. From what I read online (http://stackoverflow.com/questions/7898446/how-to-exclude-a-dependency-from-parents-project-in-maven) people also do all sorts of "hacks" to achieve this. I say we stick with this ``<scope>test</scope>`` since it's done like that in all the other projects.

**Comment by pinaf** [comment]
@amihaiemil agreed, thanks.

**Comment by pinaf** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by dmarkov** [comment]
@pinaf **19 mins** added to your account (payment number `AP-8V970013566267729`), many thanks for your contribution! 48 hours and 37 mins spent here.

you're getting extra minutes here (c=4)

+19 to your rating, your total score is [+6695](http://www.netbout.com/b/35128?open=rating)

**Comment by dmarkov** [comment]
@rultor deploy now pls

**Comment by amihaiemil** [comment]
@dmarkov can you let rultor try to deploy again?

**Comment by dmarkov** [comment]
> @dmarkov can you let rultor try to deploy again? 

@amihaiemil ask project architect. I'm only deploying once

**Comment by amihaiemil** [comment]
@yegor256 This will not be deployed successfully until issue #82 is solved. 

On other topic: 

What is the complete workflow? In general,  does the PR need to be deployed until the ticket is closed? I'm a bit confused since I have 4 or 5 other open tickets which had their PR merged and closed days ago .

**Comment by yegor256** [comment]
@amihaiemil deployment is required if you are solving and removing a puzzle

**Pull request merged**
